-- WAQTD MILLER'S MANAGER'S SALARY

SELECT SAL 
FROM SCOTT.EMP
WHERE EMPNO IN (SELECT MGR
                FROM SCOTT.EMP
                WHERE ENAME = 'MILLER');

-- WAQTD LOCATION OF SMITH'S MANAGER'S MANAGER

SELECT LOC
FROM SCOTT.DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                 FROM SCOTT.EMP
                 WHERE EMPNO IN (SELECT MGR
                                  FROM SCOTT.EMP 
                                  WHERE EMPNO IN (SELECT MGR
                                                  FROM SCOTT.EMP
                                                  WHERE ENAME = 'SMITH')));


-- waqtd NAME OF EMPLOYEE REPORTING TO BLAKE 

-- WAQTD NAME OF EMPLOYEES REPORTING TO BLAKE

SELECT ENAME 
FROM SCOTT.EMP
WHERE MGR IN (SELECT EMPNO
                FROM SCOTT.EMP
                WHERE ENAME = 'BLAKE');

SELECT *
FROM SCOTT.EMP;


-- WAQTD NUMBER OF EMPLOYEES REPORTING TO KING

SELECT count(*) 
FROM SCOTT.EMP
WHERE MGR IN (SELECT EMPNO
                FROM SCOTT.EMP
                WHERE ENAME = 'KING');


-- WAQTD DETAILS OF EMPLOYEES REPORTING TO JONES

SELECT * 
FROM SCOTT.EMP
WHERE MGR IN (SELECT EMPNO
              FROM SCOTT.EMP
              WHERE ENAME ='JONES');